### ISSUE TITLE
AttributeError: module 'kanjize' has no attribute 'int2kanji'

### ISSUE THREAD

**Issue by nakano-tomofumi** [nakano-tomofumi/normalize-japanese-addresses-py#5]
```
Traceback (most recent call last):
  ....
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/normalize.py", line 62, in normalize
    addr, town, lat, lng = normalize_after_town_names(
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/normalize.py", line 288, in normalize_after_town_names
    addr = replace_addr(addr)
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/library/regex.py", line 229, in replace_addr
    addr = pattern.sub(repl, addr)
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/library/regex.py", line 201, in <lambda>
    (re.compile("([0-9]+)(丁目)"), lambda m: replace_1(m.group())),
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/library/regex.py", line 195, in replace_1
    num.group(), kanjize.int2kanji(int(num.group())))
AttributeError: module 'kanjize' has no attribute 'int2kanji'
```

**Comment by nakano-tomofumi** [comment]
related to https://github.com/Taka710/normalize-japanese-addresses-py/issues/2
