### ISSUE TITLE
UnboundLocalError: local variable 'townAddr' referenced before assignment

### ISSUE THREAD

**Issue by nakano-tomofumi** [nakano-tomofumi/normalize-japanese-addresses-py#6]
```
Traceback (most recent call last):
  .... 
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/normalize.py", line 62, in normalize
    addr, town, lat, lng = normalize_after_town_names(
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/normalize.py", line 280, in normalize_after_town_names
    normalized = normalize_town_name(addr, pref, city, endpoint)
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/library/regex.py", line 311, in normalize_town_name
    for town, pattern, lat, lng in get_town_regexes(pref, city, endpoint):
  File "/home/nakano/work/batch/.venv/lib/python3.9/site-packages/normalize_japanese_addresses/library/regex.py", line 150, in get_town_regexes
    if (not is_kyoto and townAddr not in api_towns_set
UnboundLocalError: local variable 'townAddr' referenced before assignment
```

**Comment by nakano-tomofumi** [comment]
https://github.com/nakano-tomofumi/normalize-japanese-addresses-py/blob/main/normalize_japanese_addresses/library/regex.py#L150
